# .tbls.yml

# DSN (Database Source Name) to connect database
dsn: postgres://postgres:postgres@tbls-test_db_1:5432/postgres?sslmode=disable

# Path to generate document
# Default is `dbdoc`
docPath: doc/schema