erDiagram

"public.account_roles" }o--|| "public.accounts" : "FOREIGN KEY (user_id) REFERENCES accounts(user_id)"
"public.account_roles" }o--|| "public.roles" : "FOREIGN KEY (role_id) REFERENCES roles(role_id)"

"public.accounts" {
  integer user_id
  varchar_50_ username
  varchar_50_ password
  varchar_255_ email
  timestamp_without_time_zone created_on
  timestamp_without_time_zone last_login
}
"public.roles" {
  integer role_id
  varchar_255_ role_name
}
"public.account_roles" {
  integer user_id
  integer role_id
  timestamp_without_time_zone grant_date
}
